### ISSUE TITLE
Agent doesn't wait PROLOG_FREQ

### ISSUE THREAD

**Issue by alacn1** [OCSInventory-NG/AndroidAgent#1]
OCS Android Agent v2.1.5 report to server every wake frequency instead of inventory frequency (PROLOG_FREQ).

At server we have PROLOG_FREQ set to 5 hours and refuse forced inventory (INVENTORY_SESSION_ONLY).
Looks like android agent is sending forced inventory every 10mins (wake freq) instead of waiting PROLOG_FREQ to contact the server.

Android Agent config:
Automatic: yes
Inventory freq: 5 hours (it took from server config)
Wake freq: 10min (default)
Cache lifetime: 15min (default)

Server /var/log/ocsinventory-server/activity.log:
Tue Oct  6 15:46:57 2015;10325;102;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;prolog;declined
Tue Oct  6 15:46:57 2015;10312;318;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;session;missing
Tue Oct  6 15:46:57 2015;10312;114;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;no_session
Tue Oct  6 15:46:57 2015;10312;115;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;refused
Tue Oct  6 15:56:59 2015;11577;102;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;prolog;declined
Tue Oct  6 15:56:59 2015;11582;318;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;session;missing
Tue Oct  6 15:56:59 2015;11582;114;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;no_session
Tue Oct  6 15:56:59 2015;11582;115;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;refused
Tue Oct  6 16:06:54 2015;12704;102;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;prolog;declined
Tue Oct  6 16:06:54 2015;12711;318;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;session;missing
Tue Oct  6 16:06:54 2015;12711;114;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;no_session
Tue Oct  6 16:06:54 2015;12711;115;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;refused
Tue Oct  6 16:10:20 2015;13104;102;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;prolog;declined
Tue Oct  6 16:10:20 2015;13105;318;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;session;missing
Tue Oct  6 16:10:20 2015;13105;114;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;no_session
Tue Oct  6 16:10:20 2015;13105;115;android-2059925ffeaca57f-2015-09-29-12-55-03;10.25.40.209;OCS-NG_Android_agent_v2.1;inventory;refused

**Comment by vdeville** [comment]
Hello @alacn1,
I'm going to test this bug.
Thanks

**Comment by gillesdubois** [comment]
Hi,

This bug has been fixed and is available in the android 2.3RC :)

Regards,
Gilles Dubois.
