### ISSUE TITLE
Android 2.3 - processor speed

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/AndroidAgent#11]
Pas de remontée d'information.
Aucun des paths utilisés ne fournit l'information.

A défaut de mieux, faut-il prendre les BogoMIPS ?

**Comment by vdeville** [comment]
Hello @AnaelMobilia, 
Nous ne prenons plus en charge ces version d'android. Nous supportons toutes les versions à partir de la 4 et +.
Merci
