### ISSUE TITLE
Envoi de l'inventaire - retour

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/AndroidAgent#14]
Après envoi réussi de l'inventaire, s'affiche "NO_ACCONT_UPDATE"

**Comment by gillesdubois** [comment]
Le message est normal.

Lorsque un agent OCS ( tout OS confondu ) envoie son inventaire.
Un PROLOG_RESPONSE est aussi envoyé du serveur vers l'agent. 
Celui-ci contient toutes les mises a jour de configuration réalisée depuis le serveur  ( Fréquence d'inventaire / Activation du télé-deploiement / etc, etc.. )

Lorsque aucune mise a jour n'est faite ce PROLOG renvoie NO_ACCOUNT_UPDATE :)

L'image ci-dessous montre un peu le principe de com agent / serveur lors d'un inventaire : 

![schema_teledeploy_simple](https://cloud.githubusercontent.com/assets/9396603/19014518/45ec4c72-87ef-11e6-92f6-2b1f9e1c9f8a.jpg)

N'hésite pas si tu as besoin de plus d'infos.
Gilles Dubois.

**Comment by AnaelMobilia** [comment]
Suggestion : un catch du message de retour et affichage d'un message plus user-friendly (et traduit) ?
