### ISSUE TITLE
When permissions is not accorded, app crash when send inventory

### ISSUE THREAD

**Issue by vdeville** [OCSInventory-NG/AndroidAgent#17]
### General informations
Android version : 6, 7  

### OCS Inventory informations
Android agent version : 2.3.0

### Problem's description
When android permissions is not accorded, app crash when send inventory.
Verified in debug crash report on android studio.

**Comment by gillesdubois** [comment]
See https://github.com/OCSInventory-NG/AndroidAgent/commit/9e6baa1c6c7eb84a8769aa510e789ce7c84ded18
