### ISSUE TITLE
App crash when inventory on Galaxy TabA6

### ISSUE THREAD

**Issue by ameurou** [OCSInventory-NG/AndroidAgent#18]
### General informations
Android version :  6.0.1 on Galaxy Tab A6
Sd card in the tablet

### OCS Inventory informations
Android agent version : 2.3.0

### Problem's description
Application crash when i try to inventory the device (Send inventory or Store inventory ) : "The application stopped"

I look for logs, but even with the option ticked, no log file found...

**Comment by gillesdubois** [comment]
See https://github.com/OCSInventory-NG/AndroidAgent/commit/9e6baa1c6c7eb84a8769aa510e789ce7c84ded18
