### ISSUE TITLE
no MAC address on android 6.0

### ISSUE THREAD

**Issue by jackadam1981** [OCSInventory-NG/AndroidAgent#25]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Android version :  
android linux 6.0 
Server pack: Kernel version: 3.18.19

### OCS Inventory informations
Android agent version : 
Android Agent 2.3.1

### Problem's description
*Describe your problem here*
Access to information is basically normal, but no MAC address is obtained.

All MACs acquired by three exception terminals were wrong at 02:00:00:00:00:00.

sorry for my bed english.

**Comment by gillesdubois** [comment]
Hi,

This problem comes from Android's changes : 
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

Reagrds,
Gilles Dubois.
