### ISSUE TITLE
Migrate to gradle / AndroidStudio

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/AndroidAgent#3]
Hello,

Is it any objection to made a migration to gradle and AndroidStudio ?

Regards,
Anael

**Comment by AnaelMobilia** [comment]
Ping ? :)

**Comment by gillesdubois** [comment]
Hi,

Sorry for the delay.
No objection on this point :)

Regards,
Gilles Dubois.

**Comment by AnaelMobilia** [comment]
@MyTheValentinus  This issue isn't resolved. Please leave it open (?)

**Comment by damienbelliard** [comment]
Hi, 

Why you want to reopen this issue ? 
Have you any question about @gillesdubois post ? 

Regards

**Comment by AnaelMobilia** [comment]
@damienbelliard because the issue "Migrate to gradle / AndroidStudio" isn't resolved when @MyTheValentinus  closed the issue ?

I ask before to made the changes in the code (See my pull request #5 ).

So, as this pull request isn't merged, the project should not be migrated to Android Studio / Gradle.
And, in my opinion, the issue could stay open as reminder of a suggestion for this project ?

Regards,
Anael
