### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/AndroidAgent#4]
Hello,

Under which license should be taked the code ?
All others OCS tools appears to be under GNU GPL v2.
No license file or headers are present on this application. Nor a contributor agreement.

Contributors to this code are :
@CedricCabessa 
@cdpointpoint 
@mortheres
@... Nicolas Ricquemaque
@AnaelMobilia

Have you - in archives - an agreement from these people to take the application under GNU GPL V2 ?

**Comment by vdeville** [comment]
Hello,
All OCS Inventory project is licensed under GPLv2.
For this repo us missing licence file. 
If contributor not agree this new licence please tell us !

Thanks

**Comment by vdeville** [comment]
Commit https://github.com/OCSInventory-NG/AndroidAgent/commit/5f1ca7e91e025c7ab176ab8149c5134b6b7bf766

**Comment by AnaelMobilia** [comment]
Hi @MyTheValentinus 
Could you, please, provide a place where it's write than "'All OCS Inventory project is licensed under GPLv2." ?

It's a legal issue, not just a missing file imho :)

**Comment by damienbelliard** [comment]
Hi, 

All OCS github repo have a GNU GPL v2 Licence file exept two : 
- Wiki with a GNU Free Documentation License Version 1.3
- Agent-Deployment-Tool (it's a omission but of course, this code is under gnu gpl v2)

Regards

**Comment by gillesdubois** [comment]
This issue has been resolved.
Closing it.
